/** The typefaces the editor offers, featured first. */
export const FEATURED_FONTS = [
  "Manrope",
  "Inter",
  "DM Sans",
  "Montserrat",
  "Poppins",
  "Playfair Display",
  "Lora",
  "Open Sans",
  "Oswald",
  "Space Grotesk",
  "Anton",
  "Bebas Neue",
  "Archivo Black",
  "DM Serif Display",
  "Italiana",
  "Great Vibes",
] as const;

export const MORE_FONTS = [
  "Arial",
  "Arial Black",
  "Archivo",
  "Baskerville",
  "Cambria",
  "Courier New",
  "Franklin Gothic Medium",
  "Garamond",
  "Georgia",
  "Gill Sans",
  "Helvetica",
  "Instrument Serif",
  "Merriweather",
  "Roboto",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
] as const;
