import type { Format } from "./types";

export const platformKeys = [
  "Popular",
  "WhatsApp",
  "Instagram",
  "Facebook",
  "LinkedIn",
  "YouTube",
  "TikTok",
  "X",
  "Pinterest",
  "History",
  "Other",
] as const;

export type PlatformFilter = (typeof platformKeys)[number];

const format = (
  value: Format & {
    platform: NonNullable<Format["platform"]>;
    type: NonNullable<Format["type"]>;
    usage: string;
    previewVariant: string;
  },
): Format => value;

export const formats: Format[] = [
  format({
    id: "instagram-post",
    label: "Instagram Post",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "Instagram",
    platform: "instagram",
    type: "post",
    usage: "feed social portrait",
    popular: true,
    previewVariant: "editorial",
  }),
  format({
    id: "instagram-square",
    label: "Instagram Square",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "Instagram",
    platform: "instagram",
    type: "post",
    usage: "feed social square",
    popular: true,
    previewVariant: "geometric",
    listedInPlatform: false,
  }),
  format({
    id: "instagram-story",
    label: "Instagram Story",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "Instagram",
    platform: "instagram",
    type: "story",
    usage: "vertical ephemeral story",
    popular: true,
    previewVariant: "type",
  }),
  format({
    id: "instagram-reel",
    label: "Instagram Reel",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "Instagram",
    platform: "instagram",
    type: "reel",
    usage: "vertical short video",
    animated: true,
    popular: true,
    previewVariant: "video",
  }),
  format({
    id: "instagram-ad",
    label: "Instagram Ad",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "Instagram",
    platform: "instagram",
    type: "ad",
    usage: "advertising sponsored portrait",
    previewVariant: "product",
  }),
  format({
    id: "instagram-animated-post",
    label: "Animated Instagram Post",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "Instagram",
    platform: "instagram",
    type: "post",
    usage: "animated feed motion",
    animated: true,
    previewVariant: "tint",
  }),
  format({
    id: "instagram-feed-ad",
    label: "Instagram Feed Ad",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "Instagram",
    platform: "instagram",
    type: "ad",
    usage: "advertising sponsored square feed",
    previewVariant: "minimal",
  }),
  format({
    id: "instagram-story-ad",
    label: "Instagram Story Ad",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "Instagram",
    platform: "instagram",
    type: "ad",
    usage: "advertising sponsored vertical story",
    previewVariant: "product",
  }),

  format({
    id: "whatsapp-status",
    label: "WhatsApp Status",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "WhatsApp",
    platform: "whatsapp",
    type: "status",
    usage: "vertical ephemeral story",
    popular: true,
    previewVariant: "geometric",
  }),
  format({
    id: "whatsapp-good-morning",
    label: "Good Morning WhatsApp Status",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "WhatsApp",
    platform: "whatsapp",
    type: "status",
    usage: "greeting vertical story",
    previewVariant: "editorial",
  }),
  format({
    id: "whatsapp-good-night",
    label: "Good Night WhatsApp Status",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "WhatsApp",
    platform: "whatsapp",
    type: "status",
    usage: "greeting vertical story",
    previewVariant: "minimal",
  }),

  format({
    id: "facebook-post",
    label: "Facebook Post",
    subtitle: "1.91:1",
    width: 1200,
    height: 630,
    category: "Facebook",
    platform: "facebook",
    type: "post",
    usage: "feed social landscape",
    popular: true,
    previewVariant: "editorial",
  }),
  format({
    id: "facebook-cover",
    label: "Facebook Cover",
    subtitle: "2.63:1",
    width: 1640,
    height: 624,
    category: "Facebook",
    platform: "facebook",
    type: "cover",
    usage: "page header landscape banner",
    popular: true,
    previewVariant: "banner",
  }),
  format({
    id: "facebook-ad",
    label: "Facebook Ad",
    subtitle: "1.91:1",
    width: 1200,
    height: 628,
    category: "Facebook",
    platform: "facebook",
    type: "ad",
    usage: "advertising sponsored landscape",
    previewVariant: "product",
  }),
  format({
    id: "facebook-event-cover",
    label: "Facebook Event Cover",
    subtitle: "1.91:1",
    width: 1920,
    height: 1005,
    category: "Facebook",
    platform: "facebook",
    type: "cover",
    usage: "event header landscape",
    previewVariant: "type",
  }),
  format({
    id: "facebook-video",
    label: "Facebook Video",
    subtitle: "16:9",
    width: 1920,
    height: 1080,
    category: "Facebook",
    platform: "facebook",
    type: "video",
    usage: "landscape motion",
    animated: true,
    previewVariant: "video",
  }),
  format({
    id: "facebook-story",
    label: "Facebook Story",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "Facebook",
    platform: "facebook",
    type: "story",
    usage: "vertical ephemeral story",
    popular: true,
    previewVariant: "tint",
  }),
  format({
    id: "facebook-app-ad",
    label: "Facebook App Ad",
    subtitle: "1.91:1",
    width: 1200,
    height: 628,
    category: "Facebook",
    platform: "facebook",
    type: "ad",
    usage: "app advertising sponsored",
    previewVariant: "minimal",
  }),
  format({
    id: "facebook-shops-ad",
    label: "Facebook Shops Ad",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "Facebook",
    platform: "facebook",
    type: "ad",
    usage: "commerce product advertising",
    previewVariant: "product",
  }),
  format({
    id: "facebook-shops-cover",
    label: "Facebook Shops Cover",
    subtitle: "2.63:1",
    width: 1640,
    height: 624,
    category: "Facebook",
    platform: "facebook",
    type: "cover",
    usage: "commerce shop banner",
    previewVariant: "banner",
  }),
  format({
    id: "facebook-animated-cover",
    label: "Animated Facebook Cover",
    subtitle: "2.63:1",
    width: 1640,
    height: 624,
    category: "Facebook",
    platform: "facebook",
    type: "cover",
    usage: "page header motion banner",
    animated: true,
    previewVariant: "banner",
  }),
  format({
    id: "facebook-shops-logo",
    label: "Facebook Shops Logo",
    subtitle: "1:1",
    width: 500,
    height: 500,
    category: "Facebook",
    platform: "facebook",
    type: "profile",
    usage: "commerce shop identity logo",
    previewVariant: "profile",
  }),
  format({
    id: "facebook-feed-ad",
    label: "Facebook Feed Ad",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "Facebook",
    platform: "facebook",
    type: "ad",
    usage: "feed advertising sponsored portrait",
    previewVariant: "editorial",
  }),

  format({
    id: "linkedin-banner",
    label: "LinkedIn Background Photo",
    subtitle: "4:1",
    width: 1584,
    height: 396,
    category: "LinkedIn",
    platform: "linkedin",
    type: "background",
    usage: "personal profile header banner",
    popular: true,
    previewVariant: "banner",
  }),
  format({
    id: "linkedin-career-background",
    label: "LinkedIn Career Page Background",
    subtitle: "1.6:1",
    width: 1128,
    height: 705,
    category: "LinkedIn",
    platform: "linkedin",
    type: "background",
    usage: "company career page header",
    previewVariant: "minimal",
  }),
  format({
    id: "linkedin-carousel",
    label: "LinkedIn Carousel",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "LinkedIn",
    platform: "linkedin",
    type: "carousel",
    usage: "document multi page feed",
    previewVariant: "carousel",
  }),
  format({
    id: "linkedin-life-tab",
    label: "LinkedIn Life Tab",
    subtitle: "1.91:1",
    width: 1200,
    height: 628,
    category: "LinkedIn",
    platform: "linkedin",
    type: "background",
    usage: "company culture hero header",
    previewVariant: "banner",
  }),
  format({
    id: "linkedin-post",
    label: "LinkedIn Post",
    subtitle: "1:1",
    width: 1200,
    height: 1200,
    category: "LinkedIn",
    platform: "linkedin",
    type: "post",
    usage: "professional social feed",
    popular: true,
    previewVariant: "editorial",
  }),
  format({
    id: "linkedin-profile",
    label: "LinkedIn Profile Picture",
    subtitle: "1:1",
    width: 400,
    height: 400,
    category: "LinkedIn",
    platform: "linkedin",
    type: "profile",
    usage: "personal identity avatar",
    previewVariant: "profile",
  }),
  format({
    id: "linkedin-single-image-ad",
    label: "LinkedIn Single Image Ad",
    subtitle: "1.91:1",
    width: 1200,
    height: 627,
    category: "LinkedIn",
    platform: "linkedin",
    type: "ad",
    usage: "professional advertising sponsored",
    previewVariant: "product",
  }),
  format({
    id: "linkedin-video-ad",
    label: "LinkedIn Video Ad",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "LinkedIn",
    platform: "linkedin",
    type: "video",
    usage: "professional advertising motion",
    animated: true,
    previewVariant: "video",
  }),

  format({
    id: "x-post",
    label: "X Post",
    subtitle: "16:9",
    width: 1600,
    height: 900,
    category: "X",
    platform: "x",
    type: "post",
    usage: "social feed landscape",
    popular: true,
    previewVariant: "type",
  }),
  format({
    id: "youtube-thumbnail",
    label: "YouTube Thumbnail",
    subtitle: "16:9",
    width: 1280,
    height: 720,
    category: "YouTube",
    platform: "youtube",
    type: "thumbnail",
    usage: "video cover landscape",
    popular: true,
    previewVariant: "tint",
  }),
  format({
    id: "youtube-intro",
    label: "YouTube Intro",
    subtitle: "16:9",
    width: 1920,
    height: 1080,
    category: "YouTube",
    platform: "youtube",
    type: "video",
    usage: "video opening motion",
    animated: true,
    popular: true,
    previewVariant: "video",
  }),
  format({
    id: "tiktok-video",
    label: "TikTok Video",
    subtitle: "9:16",
    width: 1080,
    height: 1920,
    category: "TikTok",
    platform: "tiktok",
    type: "video",
    usage: "vertical short video",
    animated: true,
    popular: true,
    previewVariant: "video",
  }),
  format({
    id: "pinterest-pin",
    label: "Pinterest Pin",
    subtitle: "2:3",
    width: 1000,
    height: 1500,
    category: "Pinterest",
    platform: "pinterest",
    type: "post",
    usage: "vertical discovery pin",
    previewVariant: "product",
  }),
  format({
    id: "history-template",
    label: "History Template",
    subtitle: "4:5",
    width: 1080,
    height: 1350,
    category: "History",
    platform: "generic",
    type: "post",
    usage: "historical timeline educational archival story",
    previewVariant: "editorial",
  }),
  format({
    id: "social-post",
    label: "Social Media Post",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "Other",
    platform: "generic",
    type: "post",
    usage: "universal social square",
    popular: true,
    previewVariant: "geometric",
  }),
  format({
    id: "animated-social-post",
    label: "Animated Social Post",
    subtitle: "1:1",
    width: 1080,
    height: 1080,
    category: "Other",
    platform: "generic",
    type: "post",
    usage: "universal social square motion",
    animated: true,
    popular: true,
    previewVariant: "tint",
  }),
];

export const platforms = platformKeys;

export function platformLabel(platform?: Format["platform"]): PlatformFilter {
  const match = platforms.find(
    (item) => item.toLowerCase() === (platform ?? "generic").toLowerCase(),
  );
  return match ?? "Other";
}
