export type TemplateImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  promptHash: string;
  imageStyle: string;
  model: string;
  generatedAt: string;
  status: "pilot" | "approved";
};

/** Same slug rule as prompts.json and the template style kit IDs. */
export const templateSlug = (name: string) =>
  name.toLowerCase().replace(/\s+/g, "-");

export const templateImages: Readonly<Record<string, TemplateImage>> = {
  "product-launch": {
    src: "/template-cards/product-launch.webp",
    alt: "Retro vintage serum bottle poster with the headline Glow, bottled. and a Shop the launch button.",
    width: 864,
    height: 1080,
    promptHash: "fc5716349128",
    imageStyle: "retro-vintage",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "flash-sale": {
    src: "/template-cards/flash-sale.webp",
    alt: "Flat illustration sale poster with a smiling model, the FLASH SALE headline, and a 50% OFF badge.",
    width: 864,
    height: 1080,
    promptHash: "929575d04e36",
    imageStyle: "flat-illustration",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "fashion-editorial": {
    src: "/template-cards/fashion-editorial.webp",
    alt: "Watercolor Fashion Editorial poster showing Editorial half-body portrait of a woman in a rust knit, soft studio light, neutral backdrop with the headline THE QUIET.",
    width: 864,
    height: 1080,
    promptHash: "36db50220299",
    imageStyle: "watercolor",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "event-announcement": {
    src: "/template-cards/event-announcement.webp",
    alt: "Paper cut Event Announcement poster showing Audience facing a lit conference stage, warm amber spotlights, wide shot from the back of the room with the headline DESIGN SYSTEMS.",
    width: 864,
    height: 1080,
    promptHash: "d0b5ed2af920",
    imageStyle: "paper-cut",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "minimal-quote": {
    src: "/template-cards/minimal-quote.webp",
    alt: "Claymorphism Minimal Quote poster showing Black-and-white portrait of a designer with glasses at her desk with the headline The Daily Quote.",
    width: 864,
    height: 1080,
    promptHash: "fb2b78fadc78",
    imageStyle: "claymorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "business-card": {
    src: "/template-cards/business-card.webp",
    alt: "3D render Business Card poster with the headline Priya Raman.",
    width: 864,
    height: 1080,
    promptHash: "69f96961ca8b",
    imageStyle: "3d-render",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "restaurant-menu": {
    src: "/template-cards/restaurant-menu.webp",
    alt: "Photorealistic Restaurant Menu poster showing Overhead shot of a rustic ceramic bowl of roasted vegetables on dark linen with the headline Olive & Ember.",
    width: 864,
    height: 1080,
    promptHash: "6cbcf6e40373",
    imageStyle: "photorealistic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "party-invitation": {
    src: "/template-cards/party-invitation.webp",
    alt: "Isometric Party Invitation poster showing Cluster of glossy balloons and confetti on a hot-pink backdrop with the headline MAYA TURNS 30!.",
    width: 864,
    height: 1080,
    promptHash: "28adf133e42e",
    imageStyle: "isometric",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "job-opening": {
    src: "/template-cards/job-opening.webp",
    alt: "Vector Job Opening poster showing Engineer with glasses smiling at her desk, natural office light with the headline SENIOR FRONTEND ENGINEER.",
    width: 864,
    height: 1080,
    promptHash: "8f6b71bb6a70",
    imageStyle: "vector",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "webinar-promo": {
    src: "/template-cards/webinar-promo.webp",
    alt: "Hand-drawn sketch Webinar Promo poster showing Laptop showing a video call with two speakers and presentation slides with the headline Scaling Design Systems.",
    width: 864,
    height: 1080,
    promptHash: "286c1722c901",
    imageStyle: "hand-drawn",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "real-estate-listing": {
    src: "/template-cards/real-estate-listing.webp",
    alt: "Cyberpunk neon Real Estate Listing poster showing Modern two-storey family home with a gabled roof and front garden at golden hour with the headline Modern family home.",
    width: 864,
    height: 1080,
    promptHash: "7cb68d1ceb05",
    imageStyle: "cyberpunk-neon",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "fitness-class": {
    src: "/template-cards/fitness-class.webp",
    alt: "Anime Fitness Class poster showing Athlete mid-jump with arms raised in orange activewear, dark studio, dramatic rim light with the headline POWER HOUR.",
    width: 864,
    height: 1080,
    promptHash: "b0d571082d07",
    imageStyle: "anime",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "podcast-episode": {
    src: "/template-cards/podcast-episode.webp",
    alt: "Cinematic Podcast Episode poster showing Studio podcast microphone with purple backlight and soft haze with the headline Building in Public.",
    width: 864,
    height: 1080,
    promptHash: "4964d8714a12",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "coming-soon": {
    src: "/template-cards/coming-soon.webp",
    alt: "Neumorphism Coming Soon poster with the headline Coming Soon.",
    width: 864,
    height: 1080,
    promptHash: "2305a3ef8edc",
    imageStyle: "neumorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "customer-testimonial": {
    src: "/template-cards/customer-testimonial.webp",
    alt: "Glassmorphism Customer Testimonial poster showing Warm portrait of a bearded design lead in a bright office with the headline “HALF THE TIME, TWICE THE CRAFT.”.",
    width: 864,
    height: 1080,
    promptHash: "b10f78f17c5d",
    imageStyle: "glassmorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "seasonal-sale": {
    src: "/template-cards/seasonal-sale.webp",
    alt: "Pixel art Seasonal Sale poster showing Wrapped gift box with a red ribbon bow on a deep green backdrop with the headline GIFT SEASON.",
    width: 864,
    height: 1080,
    promptHash: "8b28ff67cd6a",
    imageStyle: "pixel-art",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "wedding-invitation": {
    src: "/template-cards/wedding-invitation.webp",
    alt: "Low poly Wedding Invitation poster showing Hand-painted floral corners framing the page with the headline Amara & Theo.",
    width: 864,
    height: 1080,
    promptHash: "4808c1b7ad0b",
    imageStyle: "low-poly",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "baby-shower-invite": {
    src: "/template-cards/baby-shower-invite.webp",
    alt: "Minimal line art Baby Shower Invite poster showing Soft nursery scene of a smiling moon, clouds, and stars in pastel blue with the headline OH BABY, IT'S LEO!.",
    width: 864,
    height: 1080,
    promptHash: "39a401ed33de",
    imageStyle: "line-art",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "graduation-announcement": {
    src: "/template-cards/graduation-announcement.webp",
    alt: "Photorealistic Graduation Announcement poster showing Thin ornamental gold border with corner flourishes with the headline Congratulations, Sofia.",
    width: 864,
    height: 1080,
    promptHash: "42d6ff6d320e",
    imageStyle: "photorealistic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "holiday-greeting-card": {
    src: "/template-cards/holiday-greeting-card.webp",
    alt: "Low poly Holiday Greeting Card poster showing Thin ornamental gold border with corner flourishes with the headline Warm Wishes.",
    width: 864,
    height: 1080,
    promptHash: "ad21bf221724",
    imageStyle: "low-poly",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "new-year-countdown": {
    src: "/template-cards/new-year-countdown.webp",
    alt: "Anime New Year Countdown poster showing Gold fireworks bursting over a night city skyline with the headline COUNTDOWN.",
    width: 864,
    height: 1080,
    promptHash: "f753f10ae42a",
    imageStyle: "anime",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "recipe-card": {
    src: "/template-cards/recipe-card.webp",
    alt: "Vector Recipe Card poster showing Overhead shot of a grain bowl with roasted squash, chickpeas, and a tahini drizzle with the headline Roasted squash grain bowl.",
    width: 864,
    height: 1080,
    promptHash: "7e00d3752409",
    imageStyle: "vector",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "travel-promo": {
    src: "/template-cards/travel-promo.webp",
    alt: "Glassmorphism Travel Promo poster showing Whitewashed village above a turquoise sea at sunset with the headline Santorini in seven nights.",
    width: 864,
    height: 1080,
    promptHash: "fe21024931ce",
    imageStyle: "glassmorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "music-concert-poster": {
    src: "/template-cards/music-concert-poster.webp",
    alt: "Cyberpunk neon Music Concert Poster poster showing Dramatic side-profile silhouette of a singer under magenta stage light with the headline THE NIGHT OWLS.",
    width: 864,
    height: 1080,
    promptHash: "4aca0681540e",
    imageStyle: "cyberpunk-neon",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "yoga-retreat": {
    src: "/template-cards/yoga-retreat.webp",
    alt: "Pixel art Yoga Retreat poster showing Person meditating cross-legged on a mat in soft morning light among trees with the headline Slow down.",
    width: 864,
    height: 1080,
    promptHash: "bf40b464059a",
    imageStyle: "pixel-art",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "book-launch": {
    src: "/template-cards/book-launch.webp",
    alt: "Cinematic Book Launch poster showing Hardcover novel with a deep red jacket standing on a stack of books with the headline The Weight of Small Things.",
    width: 864,
    height: 1080,
    promptHash: "e771f8cb3f27",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "startup-pitch-cover": {
    src: "/template-cards/startup-pitch-cover.webp",
    alt: "Minimal line art Startup Pitch Cover poster showing Clean upward growth chart on a dark dashboard with the headline Relay.",
    width: 864,
    height: 1080,
    promptHash: "4d6db8dd4aff",
    imageStyle: "line-art",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "newsletter-header": {
    src: "/template-cards/newsletter-header.webp",
    alt: "Hand-drawn sketch Newsletter Header poster showing City skyline at dawn with lit windows with the headline The Weekly Grid.",
    width: 864,
    height: 1080,
    promptHash: "4d3f6fc872a0",
    imageStyle: "hand-drawn",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "coupon-voucher": {
    src: "/template-cards/coupon-voucher.webp",
    alt: "Isometric Coupon Voucher poster with the headline Your next order over $80.",
    width: 864,
    height: 1080,
    promptHash: "a309b0a608c0",
    imageStyle: "isometric",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "product-catalog-cover": {
    src: "/template-cards/product-catalog-cover.webp",
    alt: "Retro vintage Product Catalog Cover poster showing Ceramic vases in earthy glazes on a linen-covered plinth with the headline HOME GOODS CATALOG.",
    width: 864,
    height: 1080,
    promptHash: "5e4ed6892bed",
    imageStyle: "retro-vintage",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "charity-fundraiser": {
    src: "/template-cards/charity-fundraiser.webp",
    alt: "Watercolor Charity Fundraiser poster showing Hands gently holding a heart, warm community volunteering scene with the headline EVERY MEAL MATTERS.",
    width: 864,
    height: 1080,
    promptHash: "4fb0dd78dac6",
    imageStyle: "watercolor",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "online-course-promo": {
    src: "/template-cards/online-course-promo.webp",
    alt: "Paper cut Online Course Promo poster showing Glowing lightbulb with a violet filament on a soft lavender backdrop with the headline Design Thinking Fundamentals.",
    width: 864,
    height: 1080,
    promptHash: "623a6eb1dce8",
    imageStyle: "paper-cut",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "app-launch": {
    src: "/template-cards/app-launch.webp",
    alt: "Neumorphism App Launch poster showing Smartphone showing a clean planner app with a notification, glowing blue light with the headline Plan less, live more.",
    width: 864,
    height: 1080,
    promptHash: "27828a32b087",
    imageStyle: "neumorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "anniversary-card": {
    src: "/template-cards/anniversary-card.webp",
    alt: "Flat illustration Anniversary Card poster showing Hand-painted floral corners framing the page with the headline Ten Years of Us.",
    width: 864,
    height: 1080,
    promptHash: "48dc826edd89",
    imageStyle: "flat-illustration",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "motivational-poster": {
    src: "/template-cards/motivational-poster.webp",
    alt: "Claymorphism Motivational Poster poster with the headline SMALL STEPS STILL MOVE YOU FORWARD..",
    width: 864,
    height: 1080,
    promptHash: "3c234f56ccdc",
    imageStyle: "claymorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "team-hiring-banner": {
    src: "/template-cards/team-hiring-banner.webp",
    alt: "3D render Team Hiring Banner poster showing Designer with curly hair smiling in a bright studio with the headline WE'RE HIRING.",
    width: 864,
    height: 1080,
    promptHash: "cbc3d35d5828",
    imageStyle: "3d-render",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-product-spotlight": {
    src: "/template-cards/m3-product-spotlight.webp",
    alt: "Cinematic M3 Product Spotlight poster showing Frosted spray bottle on a soft lilac pedestal, studio light with the headline Aura hydrating mist.",
    width: 864,
    height: 1080,
    promptHash: "b28b0d320504",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-event-poster": {
    src: "/template-cards/m3-event-poster.webp",
    alt: "3D render M3 Event Poster poster showing Small meetup audience facing a speaker and slides, teal lighting with the headline Material Design Night.",
    width: 864,
    height: 1080,
    promptHash: "61dc050fd362",
    imageStyle: "3d-render",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-seasonal-offer": {
    src: "/template-cards/m3-seasonal-offer.webp",
    alt: "Glassmorphism M3 Seasonal Offer poster showing Gift box with a warm amber ribbon, soft studio light with the headline SPRING OFFER.",
    width: 864,
    height: 1080,
    promptHash: "b5a5f7b0d05a",
    imageStyle: "glassmorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-editorial-cover": {
    src: "/template-cards/m3-editorial-cover.webp",
    alt: "Neumorphism M3 Editorial Cover poster showing Editorial half-body portrait of a male model in a rose-toned blazer against a tonal backdrop with the headline TONAL.",
    width: 864,
    height: 1080,
    promptHash: "60db1ce4a68b",
    imageStyle: "neumorphism",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-app-announcement": {
    src: "/template-cards/m3-app-announcement.webp",
    alt: "Flat illustration M3 App Announcement poster showing Smartphone showing an app themed from the wallpaper's colors with the headline Dynamic color is here.",
    width: 864,
    height: 1080,
    promptHash: "5537d0445833",
    imageStyle: "flat-illustration",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "m3-quote-card": {
    src: "/template-cards/m3-quote-card.webp",
    alt: "Anime M3 Quote Card poster with the headline “Color is a power which directly influences the soul.”.",
    width: 864,
    height: 1080,
    promptHash: "039fb0e0f7f1",
    imageStyle: "anime",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "street-style-fit-check": {
    src: "/template-cards/street-style-fit-check.webp",
    alt: "Candid street style Instagram post with a woman in a cream blazer and the headline today's fit.",
    width: 864,
    height: 1080,
    promptHash: "b6d3e6389dbb",
    imageStyle: "photorealistic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "everyday-skincare": {
    src: "/template-cards/everyday-skincare.webp",
    alt: "Natural skincare Instagram post showing a woman applying moisturizer and the headline a softer morning.",
    width: 864,
    height: 1080,
    promptHash: "c3bb7e45d78d",
    imageStyle: "photorealistic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "cafe-morning": {
    src: "/template-cards/cafe-morning.webp",
    alt: "Lifestyle Instagram post of a man with coffee by a cafe window and the headline coffee, then everything.",
    width: 864,
    height: 1080,
    promptHash: "708e1e9f3487",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "movement-club": {
    src: "/template-cards/movement-club.webp",
    alt: "Two candid photos of an athlete stretching in a park with the headline move at your pace.",
    width: 864,
    height: 1080,
    promptHash: "72f498485ef2",
    imageStyle: "photorealistic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "coastal-weekend": {
    src: "/template-cards/coastal-weekend.webp",
    alt: "Coastal travel Instagram post showing a woman on a seaside promenade and the headline weekend notes.",
    width: 864,
    height: 1080,
    promptHash: "bf1fb8483239",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "after-dark-sessions": {
    src: "/template-cards/after-dark-sessions.webp",
    alt: "Cinematic live music poster with an amber-lit electric guitar and the title After Dark.",
    width: 864,
    height: 1080,
    promptHash: "df66a6a26da3",
    imageStyle: "cinematic",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "studio-workshop": {
    src: "/template-cards/studio-workshop.webp",
    alt: "Vector workshop poster with a laptop on a studio desk and the title Make better things.",
    width: 864,
    height: 1080,
    promptHash: "8559a77c174b",
    imageStyle: "vector",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
  "sunday-market": {
    src: "/template-cards/sunday-market.webp",
    alt: "Flat illustration market poster with a bowl of produce and the title Sunday Market.",
    width: 864,
    height: 1080,
    promptHash: "0887d74d12b4",
    imageStyle: "flat-illustration",
    model: "OpenAI built-in image_gen",
    generatedAt: "2026-09-25",
    status: "approved",
  },
};

export function templateImageFor(name: string): TemplateImage | undefined {
  return templateImages[templateSlug(name)];
}
