import type { AssetItem } from "../types.ts";

/** Promo and CTA presets: discounts, badges and call-to-action buttons. */
export const promoItems: AssetItem[] = [
  {
    id: "promo-percent-off",
    label: "Percent off",
    category: "promo",
    kind: "offer",
    tags: ["discount", "sale", "percent", "offer", "promo", "badge"],
    prompt:
      "Percent-off offer: heavy condensed Oswald in uppercase, sits inside a rounded panel with tight padding, primary brand color fill with light high-contrast type, reads instantly at a glance",
    content: "30% OFF",
    style: {
      fontFamily: "Oswald",
      fontSize: 62,
      fontWeight: 800,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 12,
    },
    popularRank: 6,
  },
  {
    id: "promo-flat-discount",
    label: "Flat discount",
    category: "promo",
    kind: "offer",
    tags: ["discount", "sale", "flat", "offer", "money", "badge"],
    prompt:
      "Flat-amount discount badge: bold Manrope numerals with a small currency glyph, sits inside a rounded card with generous padding, secondary brand color fill and light type, unmistakable at small sizes",
    content: "$10 OFF",
    style: {
      fontFamily: "Manrope",
      fontSize: 54,
      fontWeight: 800,
      background: "$secondary",
      color: "#FFFFFF",
      borderRadius: 12,
    },
  },
  {
    id: "promo-bogo",
    label: "BOGO",
    category: "promo",
    kind: "offer",
    tags: ["bogo", "buy one get one", "offer", "sale"],
    prompt:
      "Buy-one-get-one badge: bold condensed uppercase sans-serif on two short lines, sits inside a rounded ticket panel, primary brand color fill with light high-contrast type, punchy at a glance",
    content: "BUY 1 GET 1",
    style: {
      fontFamily: "Oswald",
      fontSize: 40,
      fontWeight: 700,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 12,
    },
  },
  {
    id: "promo-coupon",
    label: "Coupon",
    category: "promo",
    kind: "offer",
    tags: ["coupon", "code", "discount", "promo"],
    prompt:
      "Coupon treatment: bold condensed uppercase sans-serif inside a rounded pill panel with generous padding, panel in the primary brand color with light high-contrast type, crisp and legible at a glance",
    content: "USE CODE: SAVE20",
    style: {
      fontFamily: "Oswald",
      fontSize: 30,
      fontWeight: 700,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
  },
  {
    id: "promo-price-tag",
    label: "Price tag",
    category: "promo",
    kind: "price",
    tags: ["price", "tag", "cost", "product"],
    prompt:
      "Product price tag: bold Manrope numerals with a small currency symbol, sits on a light rounded chip with a thin border, primary brand color ink, reads clearly next to product imagery",
    content: "$49",
    style: {
      fontFamily: "Manrope",
      fontSize: 58,
      fontWeight: 800,
      color: "$primary",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "$primary",
    },
    popularRank: 12,
  },
  {
    id: "promo-was-now",
    label: "Was/now",
    category: "promo",
    kind: "price",
    tags: ["price", "sale", "discount", "was", "now"],
    prompt:
      "Was-now price pair: old and new amounts separated by a short arrow, both in bold Manrope on one line, reads instantly as a markdown offer",
    content: "$79 → $49",
    style: { fontFamily: "Manrope", fontSize: 46, fontWeight: 700 },
  },
  {
    id: "promo-free-shipping",
    label: "Free shipping",
    category: "promo",
    kind: "badge",
    tags: ["shipping", "delivery", "free", "badge"],
    prompt:
      "Free-shipping chip: bold uppercase Inter on a single short line, sits inside a rounded pill, secondary brand color fill with light type, legible at small sizes",
    content: "FREE SHIPPING",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 700,
      background: "$secondary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
  },
  {
    id: "promo-limited-edition",
    label: "Limited edition",
    category: "promo",
    kind: "badge",
    tags: ["limited", "exclusive", "badge", "scarcity"],
    prompt:
      "Limited-edition chip: bold uppercase Montserrat with wide letter spacing, sits inside a rounded outline panel, primary brand color border and ink, feels exclusive and legible",
    content: "LIMITED EDITION",
    style: {
      fontFamily: "Montserrat",
      fontSize: 20,
      fontWeight: 700,
      letterSpacing: 1,
      color: "$primary",
      borderWidth: 2,
      borderColor: "$primary",
      borderRadius: 999,
    },
  },
  {
    id: "promo-new-arrival",
    label: "New arrival",
    category: "promo",
    kind: "badge",
    tags: ["new", "arrival", "badge", "launch"],
    prompt:
      "New-arrival chip: bold uppercase Manrope on a single short word pair, sits inside a rounded pill, primary brand color fill with light type, catches the eye without shouting",
    content: "NEW ARRIVAL",
    style: {
      fontFamily: "Manrope",
      fontSize: 22,
      fontWeight: 800,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
  },
  {
    id: "promo-best-seller",
    label: "Best seller",
    category: "promo",
    kind: "badge",
    tags: ["bestseller", "popular", "badge", "ranking"],
    prompt:
      "Best-seller chip: bold uppercase Poppins on a single short line, sits inside a rounded pill with a small star mark, secondary brand color fill with light type, reads as social proof",
    content: "★ BEST SELLER",
    style: {
      fontFamily: "Poppins",
      fontSize: 22,
      fontWeight: 700,
      background: "$secondary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
  },
  {
    id: "promo-sold-out",
    label: "Sold out",
    category: "promo",
    kind: "badge",
    tags: ["sold out", "unavailable", "badge", "status"],
    prompt:
      "Sold-out chip: bold uppercase Inter on a short single word, sits inside a rounded outline panel, neutral ink border and text, reads clearly as an inactive status",
    content: "SOLD OUT",
    style: {
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 700,
      borderWidth: 1,
      borderRadius: 999,
    },
  },
  {
    id: "promo-rating",
    label: "Rating ★",
    category: "promo",
    kind: "badge",
    tags: ["rating", "stars", "review", "badge"],
    prompt:
      "Star rating chip: five small star glyphs beside a bold numeric score in Inter, sits on a light rounded pill, primary brand color stars, reads instantly as a customer rating",
    content: "★★★★★ 4.9",
    style: {
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 700,
      color: "$primary",
      borderRadius: 999,
    },
  },
  {
    id: "promo-countdown",
    label: "Countdown",
    category: "promo",
    kind: "badge",
    tags: ["countdown", "timer", "urgency", "badge"],
    prompt:
      "Countdown timer chip: tabular Space Grotesk digits separated by thin colons, sits on a dark rounded panel, primary brand color digits with light high-contrast background, urgent and legible",
    content: "02:14:36",
    style: {
      fontFamily: "Space Grotesk",
      fontSize: 30,
      fontWeight: 700,
      background: "#18181B",
      color: "$primary",
      borderRadius: 10,
    },
  },
  {
    id: "promo-pre-order",
    label: "Pre-order",
    category: "promo",
    kind: "badge",
    tags: ["preorder", "launch", "badge", "upcoming"],
    prompt:
      "Pre-order chip: bold uppercase Manrope on two short words, sits inside a rounded pill, secondary brand color fill with light type, signals availability ahead of launch",
    content: "PRE-ORDER NOW",
    style: {
      fontFamily: "Manrope",
      fontSize: 20,
      fontWeight: 700,
      background: "$secondary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
  },
  {
    id: "promo-cta-filled",
    label: "CTA filled",
    category: "promo",
    kind: "cta",
    tags: ["cta", "button", "filled", "action"],
    prompt:
      "Filled call-to-action button: bold Manrope in sentence case, sits inside a solid rounded rectangle with generous padding, primary brand color fill with light high-contrast type, unmistakably clickable",
    content: "Shop now",
    style: {
      fontFamily: "Manrope",
      fontSize: 30,
      fontWeight: 700,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 12,
    },
  },
  {
    id: "promo-cta-pill",
    label: "CTA pill",
    category: "promo",
    kind: "cta",
    tags: ["cta", "button", "pill", "action"],
    prompt:
      "Pill-shaped call-to-action button: bold Manrope in sentence case, sits inside a fully rounded capsule with generous padding, primary brand color fill with light high-contrast type, friendly and clickable",
    content: "Get started",
    style: {
      fontFamily: "Manrope",
      fontSize: 30,
      fontWeight: 700,
      background: "$primary",
      color: "#FFFFFF",
      borderRadius: 999,
    },
    popularRank: 2,
  },
  {
    id: "promo-cta-outline",
    label: "CTA outline",
    category: "promo",
    kind: "cta",
    tags: ["cta", "button", "outline", "secondary"],
    prompt:
      "Outline call-to-action button: bold Manrope in sentence case, sits inside a rounded rectangle with a transparent center and a crisp border, primary brand color border and ink, quiet secondary action",
    content: "Learn more",
    style: {
      fontFamily: "Manrope",
      fontSize: 30,
      fontWeight: 700,
      background: "transparent",
      color: "$primary",
      borderWidth: 2,
      borderColor: "$primary",
      borderRadius: 12,
    },
  },
  {
    id: "promo-cta-arrow",
    label: "CTA arrow",
    category: "promo",
    kind: "cta",
    tags: ["cta", "button", "arrow", "action"],
    prompt:
      "Arrow call-to-action link: bold Manrope in sentence case followed by a small forward arrow glyph, sits on a transparent background, primary brand color ink, feels lightweight and direct",
    content: "Shop now →",
    style: {
      fontFamily: "Manrope",
      fontSize: 28,
      fontWeight: 700,
      background: "transparent",
      color: "$primary",
    },
  },
];
