import {
  BadgeCheck,
  BadgePercent,
  BarChart3,
  Briefcase,
  Cpu,
  Frame,
  GraduationCap,
  Globe,
  HeartPulse,
  Home,
  Layers,
  MonitorSmartphone,
  PartyPopper,
  Plane,
  Shapes,
  Share2,
  Shirt,
  Signpost,
  Smartphone,
  Snowflake,
  Sparkle,
  Sparkles,
  Sticker,
  Type,
  Users,
  UtensilsCrossed,
  Wallet,
  Minus,
  type LucideIcon,
} from "lucide-react";
import type { AssetCategoryId } from "../asset-catalog";

/** One lucide icon per category, used in section and drill-in headers. */
export const CATEGORY_ICONS: Record<AssetCategoryId, LucideIcon> = {
  text: Type,
  promo: BadgePercent,
  devices: MonitorSmartphone,
  mobile: Smartphone,
  web: Globe,
  ai: Sparkles,
  social: Share2,
  charts: BarChart3,
  shapes: Shapes,
  lines: Minus,
  frames: Frame,
  icons: Sticker,
  backgrounds: Layers,
  abstract: Sparkle,
  brand: BadgeCheck,
  people: Users,
  scenes: Signpost,
  business: Briefcase,
  food: UtensilsCrossed,
  fashion: Shirt,
  tech: Cpu,
  events: PartyPopper,
  seasonal: Snowflake,
  education: GraduationCap,
  health: HeartPulse,
  travel: Plane,
  realestate: Home,
  finance: Wallet,
};
