/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as DesignKitRouteImport } from './routes/design-kit'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptGalleryRouteImport } from './routes/prompt-gallery'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DesignProjectIdRouteImport } from './routes/design/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignKitRoute = DesignKitRouteImport.update({
  id: '/design-kit',
  path: '/design-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptGalleryRoute = PromptGalleryRouteImport.update({
  id: '/prompt-gallery',
  path: '/prompt-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignProjectIdRoute = DesignProjectIdRouteImport.update({
  id: '/design/$projectId',
  path: '/design/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/design-kit': typeof DesignKitRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/prompt-gallery': typeof PromptGalleryRoute
  '/templates': typeof TemplatesRoute
  '/design/$projectId': typeof DesignProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/design-kit': typeof DesignKitRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/prompt-gallery': typeof PromptGalleryRoute
  '/templates': typeof TemplatesRoute
  '/design/$projectId': typeof DesignProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/design-kit': typeof DesignKitRoute
  '/legal': typeof LegalRoute
  '/projects': typeof ProjectsRoute
  '/prompt-gallery': typeof PromptGalleryRoute
  '/templates': typeof TemplatesRoute
  '/design/$projectId': typeof DesignProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-kit'
    | '/design-kit'
    | '/legal'
    | '/projects'
    | '/prompt-gallery'
    | '/templates'
    | '/design/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-kit'
    | '/design-kit'
    | '/legal'
    | '/projects'
    | '/prompt-gallery'
    | '/templates'
    | '/design/$projectId'
  id:
    | '__root__'
    | '/'
    | '/brand-kit'
    | '/design-kit'
    | '/legal'
    | '/projects'
    | '/prompt-gallery'
    | '/templates'
    | '/design/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandKitRoute: typeof BrandKitRoute
  DesignKitRoute: typeof DesignKitRoute
  LegalRoute: typeof LegalRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptGalleryRoute: typeof PromptGalleryRoute
  TemplatesRoute: typeof TemplatesRoute
  DesignProjectIdRoute: typeof DesignProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-kit': {
      id: '/design-kit'
      path: '/design-kit'
      fullPath: '/design-kit'
      preLoaderRoute: typeof DesignKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-gallery': {
      id: '/prompt-gallery'
      path: '/prompt-gallery'
      fullPath: '/prompt-gallery'
      preLoaderRoute: typeof PromptGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$projectId': {
      id: '/design/$projectId'
      path: '/design/$projectId'
      fullPath: '/design/$projectId'
      preLoaderRoute: typeof DesignProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandKitRoute: BrandKitRoute,
  DesignKitRoute: DesignKitRoute,
  LegalRoute: LegalRoute,
  ProjectsRoute: ProjectsRoute,
  PromptGalleryRoute: PromptGalleryRoute,
  TemplatesRoute: TemplatesRoute,
  DesignProjectIdRoute: DesignProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
